spring:
  rabbitmq:
    username: guest
    password: guest
    virtual-host: /
    host: localhost
    port: 5672
    routing-key: routing-key
    queues:
      - ListenerTask

exchange:
  topic: exchange-topic
